# servers.<name> declares a server that you want to sync to/from.
# You must declare at least two of these.
[servers.localhost]
# The base URL of the Diskuto API server:
url = "http://localhost:8080"
# This marks the server as a "destination", where updates can be written to.
# You need at least one of these in your configuration file.
dest = true

# An example read-only server:
[servers.blog]
url = "https://blog.nfnitloop.com"

# users.<name> declare users whose content you want to sync between servers.
[users.cody]
id = "42P3FTZoCmN8DRmLSu89y419XfYfHP9Py7a9vNLfD72F"

# Max items to sync from this account:
# Default: 50
maxCount = 50

# Marks that we should also sync this user's feed.
# (i.e.: all the users they follow)
feed.sync = true

# Optional: How many items from each followed user should we sync, max?
# After we have the $n most-recent updates from that user, we'll move on to the next.
# Default: 50
# A setting <= 0 means there should be no limit.
# feed.maxCount = 50
