# servers.<name> declares a server that you want to sync to/from.
# You must declare at least two of these.
[servers.localhost]
# The base URL of the Diskuto API server:
url = "http://localhost:8080"
# This marks the server as a "destination", where updates can be written to.
# You need at least one of these in your configuration file.
dest = true

# An example read-only server:
[servers.blog]
url = "https://blog.nfnitloop.com"

# users.<name> declare users whose content you want to sync between servers.
[users.cody]
id = "42P3FTZoCmN8DRmLSu89y419XfYfHP9Py7a9vNLfD72F"

# Should we sync all users this user follows? (default: false)
sync.follows = true

# "latest" is the simplest sync mode -- just syncs the most recent $count items between servers.
sync.mode = "latest" # default
sync.count = 50 # default


[users.exampleFullSync]
id = "..."

sync.follows = true

# "Full" sync mode walks the entire history of all servers and synchronizes between them.
# !!! Use sparingly. It can be slow, and uses many more resources than an incremental sync.
sync.mode = "full"

# Checks for any file attachments that might be missing on either side of the sync.
sync.backfillAttachments = false